name: Static Site CI
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  static-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Upptime
        uses: upptime/uptime-monitor@v1.38.0
        with:
          command: site
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./site/__sapper__/export
          publish_branch: gh-pages
          cname: status.staging.matchbiz.fr
