name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Upptime
        uses: upptime/uptime-monitor@v1.38.0
        with:
          command: update
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Trigger Static Site rebuild
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: rebuild-site
